[versions]
jvmToolchain = "17"
paper = "1.20.4-R0.1-SNAPSHOT"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
minotaur = { id = "com.modrinth.minotaur", version = "2.+" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.+" }
spotless = { id = "com.diffplug.spotless", version = "6.+" }
changelog = { id = "org.jetbrains.changelog", version = "2.1.0" }